spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:searchBlog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true


kakao.search.api:
  url: https://dapi.kakao.com/v2/search/blog
  key: 696a42f278da2b36366d067daf526e9c
